apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 515101509751.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 515101509751.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: c4dbea64
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
